[package]
name = "blogo"
version = "0.1.0"
edition = "2021"

[dependencies]
ntex = { version = "2.10.0", features = ["tokio"] }
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"
